project:
  type: website
  render:
    - "*.qmd"
  post-render: quarto/scripts/restoreMarkdownToHeirarchy.sh
  #resources:

website:
  title: "Python Programming with Design Patterns: Notes"
  page-navigation: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "I: Introduction"
        contents:
          - I-introduction/chapter-01/chapter-01.qmd
          - I-introduction/chapter-02/chapter-02.qmd
          - I-introduction/chapter-03/chapter-03.qmd
          - I-introduction/chapter-04/chapter-04.qmd
      - section: II-Creational-Patterns/ii-creational-patterns.qmd
        contents:
          - II-Creational-Patterns/chapter-05/chapter-05.qmd
          - II-Creational-Patterns/chapter-06/chapter-06.qmd
          - II-Creational-Patterns/chapter-07/chapter-07.qmd
          - II-Creational-Patterns/chapter-08/chapter-08.qmd
          - II-Creational-Patterns/chapter-09/chapter-09.qmd
          - II-Creational-Patterns/chapter-10/chapter-10.qmd
      - section: III-Structural-Patterns/iii-structural-patterns.qmd
        contents:
          - III-Structural-Patterns/chapter-12/chapter-12.qmd
          - III-Structural-Patterns/chapter-13/chapter-13.qmd
          - III-Structural-Patterns/chapter-14/chapter-14.qmd

format:
  html:
    code-fold: false
    code-links:
      - repo
  gfm:
    filters:
      - quarto/scripts/strip_ansi.lua
toc: true
toc-depth: 6
format-links: false
execute:
  enabled: true
  error: true
engine: jupyter
