---
title: "Chapter 6: The Factory Method Pattern"
---

## Notes

- [Chapter 5](../chapter-05/chapter-05.qmd) demonstrates the concept of a *simple factory*
- The Factory Concept is a fundamental and common pattern in Object-Oriented Design
  - A single class acts as an authority deciding which subclass of a hierarchy is instantiated
- The **Factory Method Pattern** extends this concept
  - No single class decides which subclass to instantiate
  - Superclass defers construction to each subclass
- Programs define an abstract class that creates objects
  - Subclasses decide which object to create

- As a simple example, consider swimmers seeded into swim lanes
  - Swimmers competing in multiple heats are first sorted to compete from slowest in early heats to fastest in the last heat
    - Within a heat, the fastest swimmers are in the centre lanes
    - This is a process called *straight seeding*
  - In a championship, swimmers often swim an event twice
    - In preliminaries, everyone competes
    - In finals the top 12 of 16 compete against each other
    - To ensure greater equality, top heats are *circle seeded*
      - Fastest three swimmers are in the centre lane in the fastest three heats
      - Second fastest are in the lane next to the centre in the top three, etc.
- We want to create a program that can automatically perform this seeding for us
  - Need to create a class hierarchy to represent events and their seeding
  - The basic idea is as follows,
    - An `Event` acts as a factory class for `Seeding` via the `get_seeding` method
    - Concrete `Event` subclasses redefine `get_seeding` to control how they are seeded
      - In this case to chose which `Seeding` subclass they want to use
    - `Swimmer` is a utility class for keeping track of swimmers
- The UML below shows the rough structure

```{mermaid}
---
title: Using the Factory Pattern to create an Event Seeding System
---
classDiagram

    class Event {
        Event: +get_seeding() Seeding
    }

    class TimedFinalEvent

    class PreliminaryEvent

    Event <|-- TimedFinalEvent
    Event <|-- PreliminaryEvent

    class Seeding {
        Seeding: +get_swimmers() List~Swimmer~
    }

    class StraightSeeding

    class CircleSeeding

    Seeding <|-- StraightSeeding
    Seeding <|-- CircleSeeding

    Event --> Seeding : get_seeding()
    TimedFinalEvent ..> StraightSeeding : Creates
    PreliminaryEvent ..> CircleSeeding : Creates

    class Swimmer {
        Swimmer: +String first_name
        Swimmer: +String last_name
        Swimmer: +int age
        Swimmer: +String club
        Swimmer: +time seed_time

        Swimmer: +get_name() String
    }

    Seeding --> Swimmer : get_swimmers()
```

### The `Swimmer` Class

- The `Swimmer` class is a basic class designed to store information about a Swimmer
  - Namely,
    1. Name
    2. Age
    3. Club
    4. Seed time
    5. Seeded lane
    6. Heat
- We'll use a common Python pattern for handling object creation which is to define a generic `__init__` that accepts the required parameters
  - We then define *class methods* to handle the various ways that one might want to provide that data
    - For example, from a text file
    - Means we can extend to accept new formats like a database row by adding a new class method as opposed to re-tooling our `__init__`
    - This reduces coupling between the data storage format and the object creation mechanism
  - We provide a class method `from_str` that converts from a *delimited* string like on might get from a csv file
    - The rest of the class is a very simple class that just holds data
      - `heat` and `lane` are set to $0$ to denote they have not been set
      - Real heats and lanes are indexed from $1$

    ```python
    class Swimmer:
        """Represents a Swimmer competing in an Event

        Attributes
        ----------
        first_name: str
            swimmer's first name
        last_name: str
            swimmer's last name
        age : int
            swimmer's current age in years
        club : str
            club the swimmer is representing
        seed_time : datetime.time
            swimmer's seed time
        heat: int
            swimmer's allocated heat, 0 represents an unallocated swimmer
        lane: int
            swimmer's allocated lane, 0 represents an unallocated swimmer
        """

        @classmethod
        def from_string(cls, swimmer: str, delimiter=" ") -> Swimmer:
            """Create a swimmer from a delimited string

            Converts a delimited string into a `Swimmer`, the string is split into
            arguments to the `Swimmer` constructor by the delimiter, and must follow
            the structure below, where ``[x]`` represents a delimited chunk
            corresponding to the parameter `x`

            ``[first_name][last_name][age][club][seed_time]``

            The parameters must be represented in the following formats,

            * `first_name` - `str`
            * `last_name` - `str`
            * `age` - `int`
            * `club` - `str`
            * `seed_time` - either `%M:%S.%f` or `%S.%f`

            Parameters
            ----------
            swimmer : str
                swimmer represented as parameter delimited by the delimiter

            delimiter : str, optional
                The delimiting symbol uses to split the string, by default " "

            Returns
            -------
            Swimmer
                swimmer described by the provided string

            Raises
            ------
            ValueError
                Could not convert the provided string to a `Swimmer` instance
            """

            swimmer_parameters = swimmer.split(sep=delimiter)

            if len(swimmer_parameters) != 5:
                raise ValueError("Swimmer requires 5 parameters")

            swimmer_parameters = [parameter.strip() for parameter in swimmer_parameters]

            first_name = swimmer_parameters[0]
            last_name = swimmer_parameters[1]
            age = int(swimmer_parameters[2])
            club = swimmer_parameters[3]

            seed_time = parse_time(swimmer_parameters[4])

            return cls(first_name, last_name, age, club, seed_time)

        def __init__(
            self,
            first_name: str,
            last_name: str,
            age: int,
            club: str,
            seed_time: datetime.time,
        ):
            """
            Create a new instance based on the provided details

            Parameters
            ----------

            first_name: str
                swimmer's first name
            last_name: str
                swimmer's last name
            age : int
                swimmer's current age in years
            club : str
                club the swimmer is representing
            seed_time : datetime.time
                swimmer's seed time
            """

            self.first_name = first_name
            self.last_name = last_name
            self.age = age
            self.club = club
            self.seed_time = seed_time
            self.heat = 0
            self.lane = 0

        @property
        def name(self) -> str:
            """
            The Swimmer's full name
            """
            return self.first_name + " " + self.last_name
    ```

  - We have a very simple `parse_time` function which helps convert a string representing a seed time into an actual `datetime.time`

    ```{python}
        import datetime
            def parse_time(timecode: str) -> datetime.time:
            """Parse a seed timecode to a time

            Parameters
            ----------
            timecode : str
                seed time represented in either `%M:%S.%f` or `%S.%f` ISO format

            Returns
            -------
            `datetime.time`
                time corresponding to the provided time code

            Raises
            ------
            ValueError
                Raised if `timecode` is not in a supported format
            """
            try:
                time = datetime.time.strptime(timecode, "%M:%S.%f")
            except ValueError:
                time = datetime.time.strptime(timecode, "%S.%f")
            return time

        print("%M:%S.%f type time:", parse_time("30:30.5"))
        print("%S.%f type time:", parse_time("30.5"))
    ```


### The `Event` Class

- The `Event` class acts as our abstract base class for defining *what* seeding objects should be created
  - It is the core of our *factory method pattern*
  - We define an abstract method `seeding` which returns a `Seeding` instance
    - This is the factory method that is overwritten by specific subclasses
  - Otherwise it provides an initialiser that accepts a sequence of `Swimmer` instances and the number of lanes in each heat

  ```python
    class Event(abc.ABC):
        """
        Abstract Class representing a generic swimming event

        Subclasses should override the `seeding` factory method to create the
        appropriate seeding instance for the event type

        Attributes
        ----------
        swimmers: Sequence[Swimmer]
            swimmers competing in the event
        number_of_lanes: int
            number of lanes in each heat
        """

        def __init__(self, swimmers: Sequence[Swimmer], lanes: int):
            """
            Create a new event instance with the provided swimmers and the
            given number of lanes per heat

            Parameters
            ----------
            swimmers: Sequence[Swimmer]
                Swimmers competing in the event
            lanes: int
                Number of lanes per heat
            """
            self.number_of_lanes = lanes
            self.swimmers = swimmers

        @abc.abstractmethod
        def seeding(self) -> Seeding:
            """
            Create the seeding for the event

            Returns
            -------
            Seeding
                The seeding methodology to be used for the event
            """
            pass
  ```

- We then define two subclasses
  1. `PreliminaryEvent`
     - Implements `seeding` to return a `CircleSeeding` instance

     ```python
        class PreliminaryEvent(Event):
            """
            A Preliminary Swimming Competition Event
            """

            def seeding(self):
                return CircleSeeding(self.swimmers, self.number_of_lanes)
     ```

  2. `TimedFinalEvent`

     - Implements `seeding` to return a `StraightSeeding` instance

     ```python
        class TimedFinalEvent(Event):
            """
            A Timed Swimming Competition Event
            """

            def seeding(self):
                return StraightSeeding(self.swimmers, self.number_of_lanes)
     ```

## Summary

## Questions
